title: Jacob Kasner # your name (or website title) here
logo: "/images/image0.PNG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Rice University Trustee Scholar. <br><br>Site Under Construction. <br><br>Projects from 2021 and Earlier.
  <br><br>
  <a href="https://www.linkedin.com/in/jacob-kasner/">View My LinkedIn Profile</a>
  <br>
theme: jekyll-theme-minimal
google_analytics: UA-176180940-1 # your Google Analytics tracking ID here
