title: Jacob Kasner # your name (or website title) here
logo: "/images/image0.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Rice University Trustee Scholar who became a Data Science Sorcerer during a growth year. Majoring in Operations Research with a minor in Environmental Studies.
  One of the <a href="https://top.mlh.io/2021/profiles/jacob-allen-kasner/">top 50</a> college programmers in the world. 
  Launched Amazon Web services backend for <a href="https://www.sparrowfi.com">SparrowFinance</a>. 
  Built data translator for the Department of Defense (DoD) saving 13,806 man-hours. 
  Strong with Python and SQL.
  Presently building <a href="https://hierarking.business.site">HierarKing</a>.
  <br><br>
  <a href="https://www.linkedin.com/in/jacob-kasner/">View My LinkedIn Profile</a>
  <br>
theme: jekyll-theme-minimal
google_analytics: UA-176180940-1 # your Google Analytics tracking ID here
