title: Jacob Kasner # your name (or website title) here
logo: "/images/image0.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Rice University Trustee Scholar who became a Data Science Sorcerer during a growth year. Majoring in Operations Research with a minor in Environmental Studies.
  One of the [top 50](https://top.mlh.io/2021/profiles/jacob-allen-kasner) college programmers in the world. Launched Amazon Web services backend for [SparrowFinance](sparrowfi.com). Built data translator for the Department of Defense (DoD) saving 13,806 man-hours. Strong with Python and SQL.
  <br><br>
  <a href="https://www.linkedin.com/in/jacob-kasner-7406a81ab/">View My LinkedIn Profile</a>
  <br>
theme: jekyll-theme-minimal
google_analytics: UA-176180940-1 # your Google Analytics tracking ID here
